src/app.py
from flask import Flask
from flask import render_template

from src.common.database import Database
from src.models.headlines.views import headlines_blueprint

app= Flask(__name__)
app.config.DEBUG = True

app.secret_key = "123"

@app.before_first_request
def init_db():
    Database.initialize()

@app.route('/')
def home():
    return render_template('home.html')

app.register_blueprint(headlines_blueprint, url_prefix="/headlines")

src/models/headlines/views.py
from flask import Blueprint, render_template, redirect, url_for

from src.models.headlines.headlines import Headlines
headlines_blueprint = Blueprint('headlines', __name__)
import src.models.headlines.constant as HeadlinesConstants


@headlines_blueprint.route("/")
def index():
    headlines = Headlines.get_all()
    try:
        # try is added to avoid the TypeError when the DB is empty
        rev = Headlines.get_highest_revision()
    except TypeError:
        rev = None
    headlines_clean = []
    # keeping a copy of healines list to remove the keyword filtered ones

    for headline in headlines:
        elements = HeadlinesConstants.rm_list
        rem = False

        for elem in elements:
            if elem in str(headline.name):
                try:
                    rem = True
                    break

                except ValueError as e:
                    continue
        if not rem:
            headlines_clean.append(headline)

    return render_template('headlines/headlines_index.html', headlines=headlines_clean, rev=rev)


@headlines_blueprint.route('/deactivate/<string:headline_id>')
def deactivate_headline(headline_id):
    Headlines.find_by_id(headline_id).deactivate()
    return redirect(url_for(".index"))


@headlines_blueprint.route('/remove_all/<int:rev>')
def deactivate_all_read(rev):
    Headlines.deactivate_all_by_rev(rev)
    return redirect(url_for(".index"))

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>News Service</title>

    {% include 'html_dependencies.html'%}
<style>
.news_box {
border-style: double;
border-color: PowderBlue;
border-width: 5px;
padding: 5px;
height: 80px;

}

div.del_button {
<!--border-style: solid;-->
border-color: Black;
float: right;
width: 10%;
<!--border-style: solid;-->
}
div.headline {
<!--border-style: double;-->
border-color: Black;
float: left;
width: 90%;
<!--border-style: solid;-->
}

div.news_heading {
border-style: double;
border-color: SlateGray;
height: 100px;
border-width: 5px;
background-image: url("http://clipartview.com/wp-content/uploads/2017/03/jobs-newspaper-clipart.jpg");
background-size: 60px;
background-repeat: no-repeat;

}

div.news_chapter {

float: left;
width: 30%;
margin: 20px;

}

.news_delete_all {
width: 20%;
margin: auto;
}


</style>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>

                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <h1>the unread</h1>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">


            </ul>


        </div>

    </div>

</nav>

<div class="content container">
    {% block content%}

    {% endblock %}
</div>


</body>
</html>

src/templates/headlines/headlines.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/headlines/headlines_index.html
{% extends "base.html" %}
{% block content %}
<div class="news_heading">
    <div class="news_chapter">
    <h1>Headlines</h1>
    </div>
    <!--<div class="news_delete_all">-->
    <!--<a class="btn btn-danger btn-sm" href="{{ url_for('headlines.deactivate_all_read', rev=rev) }}">Remove All</a>-->
    <!--</div>-->
</div>



{% for headline in headlines if headline.read_status == False %}

<div class="news_box">

    <!--<div class="del_button">-->
    <!--<a class="btn btn-danger btn-sm" href="{{ url_for('headlines.deactivate_headline', headline_id=headline._id) }}"-->
       <!--role="button">remove</a>-->
    <!--</div>-->

    <div class="headline">
    <a class="col-md-6" href="{{ headline.link }}" role="button" target="_blank">{{ headline.name }}</a>
    </div>

</div>

{% endfor %}
<div class="news_box">
<a class="btn btn-danger btn-sm news_delete_all" href="{{ url_for('headlines.deactivate_all_read', rev=rev) }}">Remove All</a>
</div>

{% endblock %}
<div class="page-header"></div>

src/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <h1>News</h1> <p>Save time from browsing the news, for updated headlines click Headlines</p>

<p><a class="btn btn-primary btn-lg" href="{{ url_for('headlines.index')}}" role="button">Headlines</a></p>


</div>
{% endblock %}

src/templates/html_dependencies.html
<!--<link rel="stylesheet" href="{{ url_for('static', filename='news-read/src/static/styles.css') }}" type="text/css">-->
<link rel="stylesheet" href="static/style.css" type="text/css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>